In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Ames_Housing_No_Missing_Data only.csv')

In [3]:
df.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,3,2010,WD,Normal,189900

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2835 entries, 0 to 2834
Data columns (total 76 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MS SubClass      2835 non-null   int64
 1   MS Zoning        2835 non-null   object
 2   Lot Frontage     2835 non-null   float64
 3   Lot Area         2835 non-null   int64
 4   Street           2835 non-null   object
 5   Lot Shape        2835 non-null   object
 6   Land Contour     2835 non-null   object
 7   Utilities        2835 non-null   object
 8   Lot Config       2835 non-null   object
 9   Land Slope       2835 non-null   object
 10  Neighborhood     2835 non-null   object
 11  Condition 1      2835 non-null   object
 12  Condition 2      2835 non-null   object
 13  Bldg Type        2835 non-null   object
 14  House Style      2835 non-null   object
 15  Overall Qual     2835 non-null   int64
 16  Overall Cond     2835 non-null   int64
 17  Year Built       2835 non-null   int64
 18  Year Remod/Add   2835 non-null   int64
 19  Roof Style       2835 non-null   object
 20  Roof Matl        2835 non-null   object
 21  Exterior 1st     2835 non-null   object
 22  Exterior 2nd     2835 non-null   object
 23  Mas Vnr Type     2835 non-null   object
 24  Mas Vnr Area     2835 non-null   float64
 25  Exter Qual       2835 non-null   object
 26  Exter Cond       2835 non-null   object
 27  Foundation       2835 non-null   object
 28  Bsmt Qual        2758 non-null   object
 29  Bsmt Cond        2758 non-null   object
 30  Bsmt Exposure    2755 non-null   object
 31  BsmtFin Type 1   2758 non-null   object
 32  BsmtFin SF 1     2835 non-null   float64
 33  BsmtFin Type 2   2758 non-null   object
 34  BsmtFin SF 2     2835 non-null   float64
 35  Bsmt Unf SF      2835 non-null   float64
 36  Total Bsmt SF    2835 non-null   float64
 37  Heating          2835 non-null   object
 38  Heating QC       2835 non-null   object
 39  Central Air      2835 non-null   object
 40  Electrical       2834 non-null   object
 41  1st Flr SF       2835 non-null   int64
 42  2nd Flr SF       2835 non-null   int64
 43  Low Qual Fin SF  2835 non-null   int64
 44  Gr Liv Area      2835 non-null   int64
 45  Bsmt Full Bath   2835 non-null   float64
 46  Bsmt Half Bath   2835 non-null   float64
 47  Full Bath        2835 non-null   int64
 48  Half Bath        2835 non-null   int64
 49  Bedroom AbvGr    2835 non-null   int64
 50  Kitchen AbvGr    2835 non-null   int64
 51  Kitchen Qual     2835 non-null   object
 52  TotRms AbvGrd    2835 non-null   int64
 53  Functional       2835 non-null   object
 54  Fireplaces       2835 non-null   int64
 55  Fireplace Qu     1429 non-null   object
 56  Garage Type      2684 non-null   object
 57  Garage Yr Blt    2835 non-null   float64
 58  Garage Finish    2682 non-null   object
 59  Garage Cars      2835 non-null   float64
 60  Garage Area      2835 non-null   float64
 61  Garage Qual      2682 non-null   object
 62  Garage Cond      2682 non-null   object
 63  Paved Drive      2835 non-null   object
 64  Wood Deck SF     2835 non-null   int64
 65  Open Porch SF    2835 non-null   int64
 66  Enclosed Porch   2835 non-null   int64
 67  3Ssn Porch       2835 non-null   int64
 68  Screen Porch     2835 non-null   int64
 69  Pool Area        2835 non-null   int64
 70  Misc Val         2835 non-null   int64
 71  Mo Sold          2835 non-null   int64
 72  Yr Sold          2835 non-null   int64
 73  Sale Type        2835 non-null   object
 74  Sale Condition   2835 non-null   object
 75  SalePrice        2835 non-null   int64
dtypes: float64(11), int64(26), object(39)
memory usage: 1.6+ MB

In [5]:
percent_missing = df.isnull().sum() * 100 / len(df)

percent_missing = percent_missing[percent_missing > 0].sort_values()

percent_missing

Electrical         0.035273
Bsmt Qual          2.716049
Bsmt Cond          2.716049
BsmtFin Type 1     2.716049
BsmtFin Type 2     2.716049
Bsmt Exposure      2.821869
Garage Type        5.326279
Garage Finish      5.396825
Garage Qual        5.396825
Garage Cond        5.396825
Fireplace Qu      49.594356
dtype: float64

In [6]:
bsmt=['Bsmt Qual','Bsmt Cond','BsmtFin Type 1','BsmtFin Type 2','Bsmt Exposure']

# combine all basement into a variables

df[bsmt]

df.dtypes[['Bsmt Qual','Bsmt Cond','BsmtFin Type 1','BsmtFin Type 2','Bsmt Exposure']]

# all the features are object

df[bsmt]=df[bsmt].fillna('NA')

# fill the data in all the features with NA (from notepad)

In [7]:
garage=['Garage Type','Garage Finish','Garage Qual','Garage Cond']

# combine all garage features into one variables

df[garage]

df[garage].isnull().sum()

df.dtypes[['Garage Type','Garage Finish','Garage Qual','Garage Cond']]

# all the features is object 

df[garage]=df[garage].fillna('NA') 

# fill all missing value in the feature with NA (from notepad)

In [8]:
df['Fireplace Qu']=df['Fireplace Qu'].fillna('NA')

# fill the missing data with NA (from notepad)

In [9]:
percent_missing = df.isnull().sum() * 100 / len(df)

percent_missing = percent_missing[percent_missing > 0].sort_values()

percent_missing

Electrical    0.035273
dtype: float64

## ENCODE STRINGS TO INTERGER

Mapping and replace - https://www.geeksforgeeks.org/mapping-external-values-to-dataframe-values-in-pandas/

## 1. Ordinal Encoding

where the item had a relationship between each item

example = excellent,good,average,poor

In [10]:
df.head(3)

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,12500,6,2010,WD,Normal,172000

In [11]:
lotshapper={'Reg':0,'IR1':1,'IR2':2,'IR3':3}

df = df.replace({"Lot Shape":lotshapper})

# create a dictionary (item:numerical value)

# replace the original strings to numerical value

# import the value from the dictionary

In [12]:
slope={'Gtl':0,'Mod':1,'Sev':2}

df = df.replace({"Land Slope":slope})

In [13]:
yesno={'Y':0,'N':1}

df=df.replace({"Central Air":yesno})

In [14]:
fin={'Fin':0,'RFn':1,'Unf':2,'NA':3}

df=df.replace({'Garage Finish':fin})

In [15]:
expo={'Gd':0,'Av':1,'Mn':2,'No':3,'NA':4}

df = df.replace({'Bsmt Exposure':expo})

In [16]:
qual={'Ex':0,'Gd':1,'TA':2,'Fa':3,'Po':4,'NA':5}

df = df.replace({"Exter Qual":qual})
df = df.replace({"Exter Cond":qual})
df = df.replace({"Bsmt Qual":qual})
df = df.replace({"Bsmt Cond":qual})
df = df.replace({"Heating QC":qual})
df = df.replace({"Kitchen Qual":qual})
df = df.replace({"Fireplace Qu":qual})
df = df.replace({"Garage Qual":qual})
df = df.replace({"Garage Cond":qual})

## 2. One Hot Encoding

when the item in a feature doesnt have a relationship that connects whole feature (subjective // different answer)

example = Colour = [ red , blue , green ] [0. , 0. , 1.]

In [17]:
df=pd.get_dummies(df,columns=['MS SubClass'],prefix='MSClass',drop_first=True)

# use pd.get_dummies for one hot
# prefix = the index name for the new features
# drop first is remove the first item in the features (else...)

In [18]:
df=pd.get_dummies(df,columns=['MS Zoning'],prefix='MSZone',drop_first=True)

In [19]:
df=pd.get_dummies(df,columns=['Street'],prefix='S',drop_first=True)

In [20]:
df=pd.get_dummies(df,columns=['Lot Config'],prefix='LCfg',drop_first=True)

In [21]:
df=pd.get_dummies(df,columns=['Utilities'],prefix='Utl',drop_first=True)

In [22]:
df=pd.get_dummies(df,columns=['Land Contour'],prefix='LC',drop_first=True)

In [23]:
df=pd.get_dummies(df,columns=['Neighborhood'],prefix='Hood',drop_first=True)

In [24]:
df=pd.get_dummies(df,columns=['Condition 1'],prefix='Cdtn1',drop_first=True)

In [25]:
df=pd.get_dummies(df,columns=['Condition 2'],prefix='Cdtn2',drop_first=True)

In [26]:
df=pd.get_dummies(df,columns=['Bldg Type'],prefix='BldgType',drop_first=True)

In [27]:
df=pd.get_dummies(df,columns=['House Style'],prefix='HStyle',drop_first=True)

In [28]:
df=pd.get_dummies(df,columns=['Roof Style'],prefix='RStyle',drop_first=True)

In [29]:
df=pd.get_dummies(df,columns=['Roof Matl'],prefix='RMatl',drop_first=True)

In [30]:
df=pd.get_dummies(df,columns=['Exterior 1st'],prefix='Ex1',drop_first=True)

In [31]:
df=pd.get_dummies(df,columns=['Exterior 2nd'],prefix='Ex2',drop_first=True)

In [32]:
df=pd.get_dummies(df,columns=['Mas Vnr Type'],prefix='MVType',drop_first=True)

In [33]:
df=pd.get_dummies(df,columns=['BsmtFin Type 1'],prefix='BT1',drop_first=True)

In [34]:
df=pd.get_dummies(df,columns=['BsmtFin Type 2'],prefix='BT2',drop_first=True)

In [35]:
df=pd.get_dummies(df,columns=['Heating'],prefix='Heat',drop_first=True)

In [36]:
df=pd.get_dummies(df,columns=['Electrical'],prefix='Elt',drop_first=True)

In [37]:
df=pd.get_dummies(df,columns=['Foundation'],prefix='Fdn',drop_first=True)

In [38]:
df=pd.get_dummies(df,columns=['Functional'],prefix='Func',drop_first=True)

In [39]:
df=pd.get_dummies(df,columns=['Garage Type'],prefix='GarType',drop_first=True)

In [40]:
df=pd.get_dummies(df,columns=['Paved Drive'],prefix='PvDri',drop_first=True)

In [41]:
df=pd.get_dummies(df,columns=['Sale Type'],prefix='SaleType',drop_first=True)

In [42]:
df=pd.get_dummies(df,columns=['Sale Condition'],prefix='SaleCond',drop_first=True)

## save clean dataset

In [43]:
df

,Lot Frontage,Lot Area,Lot Shape,Land Slope,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,Exter Qual,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_VWD,SaleType_WD,SaleCond_AdjLand,SaleCond_Alloca,SaleCond_Family,SaleCond_Normal,SaleCond_Partial
0,141.000000,31770,1,0,6,5,1960,1960,112.0,2,...,0,0,0,0,1,0,0,0,1,0
1,80.000000,11622,0,0,5,6,1961,1961,0.0,2,...,0,0,0,0,1,0,0,0,1,0
2,81.000000,14267,1,0,6,6,1958,1958,108.0,2,...,0,0,0,0,1,0,0,0,1,0
3,93.000000,11160,0,0,7,5,1968,1968,0.0,1,...,0,0,0,0,1,0,0,0,1,0
4,74.000000,13830,1,0,5,5,1997,1998,0.0,2,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830,37.000000,7937,1,0,6,6,1984,1984,0.0,2,...,0,0,0,0,1,0,0,0,1,0
2831,75.157303,8885,1,1,5,5,1983,1983,0.0,2,...,0,0,0,0,1,0,0,0,1,0
2832,62.000000,10441,0,0,5,5,1992,1992,0.0,2,...,0,0,0,0,1,0,0,0,1,0
2833,77.000000,10010,0,1,5,5,1974,1975,0.0,2,...,0,0,0,0,1,0,0,0,1,0
2834,74.000000,9627,0,1,7,5,1993,1994,94.0,2,...,0,0,0,0,1,0,0,0,1,0

In [45]:
df.to_csv('Ames_Housing_Clean_Data_no_remove_skew.csv',index=False)